defaults:
  - estimator_hyperparams: default
  - reg_model_hyperparams: default
  - setting: default
hydra:
  run:
    dir: ./logs/is_timeseries_split=${setting.is_timeseries_split}/behavior_policy=${setting.behavior_policy}/campaign=${setting.campaign}/reg_model=${setting.reg_model}/sample_size=${setting.sample_size}/n_deficient_actions=${setting.n_deficient_actions}
  sweep:
    dir: ./logs/is_timeseries_split=${setting.is_timeseries_split}/behavior_policy=${setting.behavior_policy}/campaign=${setting.campaign}/reg_model=${setting.reg_model}/sample_size=${setting.sample_size}/n_deficient_actions=${setting.n_deficient_actions}
    subdir: ./
